WebM/WebM/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebM.Models;
using WebM.Models.Gateway;

namespace WebM.Controllers
{
    public class MapController : Controller
    {
        private CenterGatewayDB db = new CenterGatewayDB();

        private ReportGatewayDB reportGateway = new ReportGatewayDB();

        public ActionResult Index()
        {




            return View();
        }

        public ActionResult GetResult(string diseaseName, string dateOne, string dateTwo)
        {
            List<long> TotalEffectedPeople = new List<long>();
            TotalEffectedPeople = reportGateway.SearchMapData(diseaseName, dateOne, dateTwo);


            return View(TotalEffectedPeople);
        }

        public ActionResult GetDiseases()
        {
            var diseases = db.Diseases.ToList();
            return Json(diseases, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ConvertDate(string date)
        {

            object[] dateObjects = new object[1];

            dateObjects[0] = new { Id = 1, Value = Convert.ToString(Convert.ToDateTime(date)) };

            var fullDate = dateObjects.ToList();
            return Json(fullDate, JsonRequestBehavior.AllowGet);
        }
	}
}

WebM/WebM/Views/Map/GetResult.cshtml
@model List<long>
@{
    Layout = null;
}

<html>
<head>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["geochart"]});
      google.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {

        var data = google.visualization.arrayToDataTable([
          ['Diseasce', 'Effected People'],
          ['BD-A', @Model[0]],
          ['BD-B', @Model[1]],
          ['BD-C', @Model[2]],
          ['BD-D', @Model[3]],
          ['BD-E', @Model[4]],
          ['BD-F', @Model[5]],
		  ['BD-G', @Model[6]]
        ]);

        var options = {
			backgroundColor: '#81d4fa',
			legend: 'none',
			datalessRegionColor: '#ffffff',
			displayMode: 'regions',
			enableRegionInteractivity: 'true',
			resolution: 'provinces',
			colorAxis: {values : ['0','11','31','51'],colors: ['#ffffff','#ffef99', 'orange', 'red']},
			sizeAxis: {minValue: 1, maxValue:1,minSize:10,  maxSize: 10},
			region:'BD',
			keepAspectRatio: true,
			width:1000,
			height:700,
			tooltip: {textStyle: {color: '#ff0000 '}, trigger:'focus'}

		};

        var chart = new google.visualization.GeoChart(document.getElementById('regions_div'));

        chart.draw(data, options);
      }
    </script>
</head>
<body>
    <div id="regions_div" style="width: 900px; height: 500px;"></div>
</body>
</html>

WebM/WebM/Views/Map/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br /><br /><br /><br />

@using (Html.BeginForm("GetResult", "Map"))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="diseaseInfo" class="control-label col-md-2">Disease</label>
        <div class="col-md-6">
            <select class="form-control " name="diseaseName" id="diseaseName"></select>
        </div>
        <div class="col-md-4">
            <button type="submit" class="btn btn-default btn-lg col-md-offset-2 col-md-8 col-xs-12" id="submitButton" value="Submit">Show Map</button>
        </div>
    </div>
    <br />
    <br />
    <hr />
    <br />
    <br />
    <div>
        <div class="form-group">
            <label for="dateInfo" class="control-label col-md-2">Date Between </label>
            <div class="col-md-4">
                <input type="text" name="dateOne" id="dateOne" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label for="dateInfo" class="control-label col-md-2">And</label>
            <div class="col-md-4">
                <input type="text" name="dateTwo" id="dateTwo" class="form-control">
            </div>
        </div>
    </div>
    <br />
    <br />
    <hr />

}

@section Scripts {
    <script>

        $(document).ready(function () {


            $('#dateOne').datepicker({

            });

            $('#dateTwo').datepicker({

            });

            var dateDataOne;
            var dateDataTwo;
            $('#dateOne').change(function () {
                var optionSelected = $(this).val();
                var myData = { date: optionSelected };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("ConvertDate", "Map")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(myData),
                    dataType: "json",
                    success: function (data) {
                        dateDataOne = data[0].Value;
                    }

                });
            });

            $('#dateTwo').change(function () {
                var optionSelected = $(this).val();
                var myData = { date: optionSelected };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("ConvertDate", "Map")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(myData),
                    dataType: "json",
                    success: function (data) {
                        dateDataTwo = data[0].Value;
                    }

                });
            });


            $.ajax({
                type: "POST",
                url: '@Url.Action("GetDiseases", "Map")',
                contentType: "application/json; charset=utf-8",

                success: function (data) {
                    $('#diseaseName').empty().append('<option value="">Select Disease</option>');
                    $.each(data, function (index, value) {
                        $('#diseaseName').append($('<option />', {
                            value: value.DiseaseId,
                            text: value.Name
                        }));
                    });
                },
            });


            $('#showDetailButton').click(function () {

                var diseaseId = $('#diseaseName option:selected').index();

                var myData = { DiseaseId: diseaseId, DateOne: dateDataOne, DateTwo: dateDataTwo };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetResult", "Map")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(myData),
                    dataType: "json",

                });
            });

        });
    </script>
}