WebM/WebM/Models/Medicine.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebM.Models;

namespace WebM.Models
{
    public class Medicine
    {
        public int MedicineId { get; set; }
        public string GenericName { get; set; }
        public double Quantity { get; set; }
        public string QuantityUnit { get; set; }



        public virtual ICollection<CenterMedicine> CenterMedicines { get; set; }
       



    }
}

WebM/WebM/Controllers/MedicineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebM.Models;
using WebM.Models.Gateway;
using WebM.Models.GatewayDB;

namespace WebM.Controllers
{
    public class MedicineController : Controller
    {
        private CenterGatewayDB db = new CenterGatewayDB();

        // GET: /Medicine/
        public ActionResult Index()
        {
            return View(db.Medicines.ToList());
        }

        // GET: /Medicine/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // GET: /Medicine/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Medicine/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

        public ActionResult Create(string GenericName, string Quantity, string UnitQuantity)
        {
            Medicine medicine = new Medicine();
            medicine.GenericName = GenericName;
            medicine.Quantity = Convert.ToInt32(Quantity);
            medicine.QuantityUnit = UnitQuantity;

            if (ModelState.IsValid)
            {
                db.Medicines.Add(medicine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(medicine);
        }

        // GET: /Medicine/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // POST: /Medicine/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MedicineId,GenericName,Quantity,QuantityUnit")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medicine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(medicine);
        }

        // GET: /Medicine/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // POST: /Medicine/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medicine medicine = db.Medicines.Find(id);
            db.Medicines.Remove(medicine);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult GetUnit()
        {
            object[] dataObjects = new object[2];

            dataObjects[0] = new { Id = 1, Value = "mg" };
            dataObjects[1] = new { Id = 2, Value = "ml" };

            var fullData = dataObjects.ToList();
            return Json(fullData, JsonRequestBehavior.AllowGet);
        }
        public ActionResult CheckUnique(string GenericName, string Quantity, string UnitQuantity)
        {
            object[] dataObjects = new object[1];

            MedicineGatewayDB aGateway = new MedicineGatewayDB();
            if (aGateway.CheckUnique(GenericName, Quantity, UnitQuantity).Equals("false"))
            {
                dataObjects[0] = new { Id = 1, Value = "false" };
            }
            else
            {
                dataObjects[0] = new { Id = 1, Value = "true" };
            }
            var fullData = dataObjects.ToList();
            return Json(fullData, JsonRequestBehavior.AllowGet);
        }
    }
}

WebM/WebM/Views/Medicine/Create.cshtml
@model WebM.Models.Medicine

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Medicine</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.GenericName, new { @class = "control-label col-md-2" })
            <input type="text" name="GenericName" id="genericName" class="form-control col-md-6">

        </div>
        <div>
            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, new { @class = "control-label col-md-2" })
                <input type="text" name="Quantity" id="quantity" class="form-control col-md-6">
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.QuantityUnit, new { @class = "control-label col-md-2" })
                <select class="form-control col-md-4" id="unitQuantity"></select>
            </div>
        </div>
        <div class="form-group">
            <input type="button" value="Create" class="btn btn-default btn-lg col-md-offset-2 col-md-8" id="createButton" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    <script>
        $(document).ready(function () {

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetUnit", "Medicine")',
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $('#unitQuantity').empty().append('<option value="">Select Unit</option>');
                    $.each(data, function (index, valueo) {
                        $('#unitQuantity').append($('<option />', {
                            value: valueo.Id,
                            text: valueo.Value
                        }));
                    });
                },
            });


            $("#unitQuantity").change(function () {
                var optionSelected = $(this).find("option:selected");
                var myData = { GenericName: $('#genericName').val(), Quantity: $('#quantity').val(), UnitQuantity: $('#unitQuantity option:selected').text() };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("CheckUnique", "Medicine")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(myData),
                    dataType: "json",
                    success: function (data) {

                        if (data[0].Value=="false") {
                            $('#genericName').val("");
                            $('#quantity').val("");
                            alert("This medicine already exist");
                        }
                      
                    },
                });
            });

            $('#createButton').click(function () {


                var myData = { GenericName: $('#genericName').val(), Quantity: $('#quantity').val(), UnitQuantity: $('#unitQuantity option:selected').text() };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Create", "Medicine")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(myData),
                    dataType: "json"

                });
            });

        });
    </script>
}

WebM/WebM/Views/Medicine/Delete.cshtml
@model WebM.Models.Medicine

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Medicine</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GenericName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenericName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuantityUnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuantityUnit)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebM/WebM/Views/Medicine/Details.cshtml
@model WebM.Models.Medicine

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Medicine</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GenericName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenericName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuantityUnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuantityUnit)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MedicineId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebM/WebM/Views/Medicine/Edit.cshtml
@model WebM.Models.Medicine

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Medicine</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.MedicineId)

        <div class="form-group">
            @Html.LabelFor(model => model.GenericName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GenericName)
                @Html.ValidationMessageFor(model => model.GenericName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity)
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityUnit, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantityUnit)
                @Html.ValidationMessageFor(model => model.QuantityUnit)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebM/WebM/Views/Medicine/Index.cshtml
@model IEnumerable<WebM.Models.Medicine>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GenericName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuantityUnit)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.GenericName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QuantityUnit)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MedicineId }) |
            @Html.ActionLink("Details", "Details", new { id=item.MedicineId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MedicineId })
        </td>
    </tr>
}

</table>