WebM/WebM/Models/Doctor.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebM.Models
{
    public class Doctor
    {

        public int DoctorId { get; set; }

        [Display(Name = "Doctor's Name")]
        public string Name { get; set; }

        [Display(Name = "Doctor's Degree")]
        public string Degree { get; set; }

        [Display(Name = "Doctor's Speciality")]
        public string Speciality { get; set; }

        public int CenterId { get; set; }



    }
}

WebM/WebM/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebM.Models;

namespace WebM.Controllers
{
    public class DoctorController : Controller
    {
        private CenterGatewayDB db = new CenterGatewayDB();

        // GET: /Doctor/
        public ActionResult Index()
        {
            if (Session["CenterId"] != null)
            {
                int centerId = (int)Session["CenterId"];
                return View(db.Doctors.ToList());
            }
            else
            {
                return RedirectToAction("LoginFailed", "Logger");
            }

        }

        // GET: /Doctor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // GET: /Doctor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Doctor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

        public ActionResult Create(string Name, string Degree, string Speciality)
        {
            Doctor aDoctor = new Doctor();
            aDoctor.Name = Name;
            aDoctor.Degree = Degree;
            aDoctor.Speciality = Speciality;
            aDoctor.CenterId = Convert.ToInt32(Session["CenterId"].ToString());
            if (ModelState.IsValid)
            {
                db.Doctors.Add(aDoctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: /Doctor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: /Doctor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DoctorId,Name,Degree,Speciality,CenterId")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: /Doctor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: /Doctor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




    }
}

WebM/WebM/Views/Doctor/Create.cshtml
@model WebM.Models.Doctor

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Doctor</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="doctorName" id="doctorName" class="form-control">
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Degree, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="Degreedoctor" id="doctorDegree" class="form-control">
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Speciality, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="doctorSpeciality" id="doctorSpeciality" class="form-control">
            </div>
        </div>

  

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Create" class="btn btn-default" id="createButton" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    <script>

        $(document).ready(function() {


            $('#createButton').click(function () {

    
                var myData = { Name: $('#doctorName').val(), Degree: $('#doctorDegree').val(), Speciality: $('#doctorSpeciality').val() };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Create", "Doctor")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(myData),
                    dataType: "json"

                });
            });

        });
    </script>
}

WebM/WebM/Views/Doctor/Delete.cshtml
@model WebM.Models.Doctor

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Degree)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Degree)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Speciality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Speciality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CenterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CenterId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebM/WebM/Views/Doctor/Details.cshtml
@model WebM.Models.Doctor

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Doctor</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Degree)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Degree)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Speciality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Speciality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CenterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CenterId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DoctorId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebM/WebM/Views/Doctor/Edit.cshtml
@model WebM.Models.Doctor

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Doctor</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.DoctorId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Degree, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Degree)
                @Html.ValidationMessageFor(model => model.Degree)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Speciality, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Speciality)
                @Html.ValidationMessageFor(model => model.Speciality)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CenterId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CenterId)
                @Html.ValidationMessageFor(model => model.CenterId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebM/WebM/Views/Doctor/Index.cshtml
@model IEnumerable<WebM.Models.Doctor>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Degree)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Speciality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CenterId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Degree)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Speciality)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CenterId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DoctorId }) |
            @Html.ActionLink("Details", "Details", new { id=item.DoctorId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.DoctorId })
        </td>
    </tr>
}

</table>